### ISSUE TITLE
Unexpected behavior - Matching object is flattened

### ISSUE THREAD

**Issue by KastanDay** [STORM-IRIT/OpenGR#9] opened 2018-08-02 14:01 UTC
Hello,
I'm experiencing a weird glitch where the object (green) is being badly deformed in a ways that shouldn't happen when it's being matched to the scene (purple).  This flattening glitch occurs as frequently as 50% of the time :( sometimes more, oftentimes less.

Have you experienced this behavior before? Any idea how I could prevent it, or catch when it happens so my robot doesn't try to grab the floor? 
Thank you very much!

Example of expected behavior:
![goodmatch](https://user-images.githubusercontent.com/13607221/43588072-b736d852-9639-11e8-99fa-20b71e517bed.png)

An example of bad behavior - object is 'flattened':
![flatmatch](https://user-images.githubusercontent.com/13607221/43588091-c378ea38-9639-11e8-9507-7a508488cb44.png)
Another example of bad behavior:
![flatmatch2](https://user-images.githubusercontent.com/13607221/43588113-cd51935c-9639-11e8-9035-7eebcfdfec30.png)
When this 'flattening' occurs there is no indication from the statistical output (it returns very high, but non 1.0, final scores) 
```
// Output for a bad, 'flattened', match
===============================
norm_max_dist: 0.09
Initial LCP: 0.555556
> Final score: 0.972222
PCA Alignment took 2399ms.
===============================
    |  0.002 -1.341 -0.018 |
R = |  -0.005 -0.247  0.003 |
    | -0.006  0.373  0.002 |

t = < -0.104, 0.209, 0.874 >
```

**Comment by nmellado** [comment] 2018-08-09 07:27
Hi @KastanDay ,

Thanks for the report.
Do you observe similar glitches when running 4PCS instead of Super4PCS (`-x` option) ? 
Also, can you provide a test dataset so I can reproduce the error ?

Cheers,

**Comment by j-polden** [comment] 2018-09-29 15:39
For what it is worth, I have also experienced this bug. The rotation matrix produced by the algorithm is not normalised in each of the component x-y-z direction vectors, which causes a skew when the pointcloud is transformed. I did not investigate further, but was able to mitigate the bug by altering the parameters somewhat.

**Comment by nmellado** [comment] 2018-09-29 18:18
Thanks for your report.
Do you still have a dataset+parameters causing this behavior ?

**Comment by KastanDay** [comment] 2018-09-30 17:08
Sorry for being AFK. I no longer have access to this info or data sets (I was working as a summer intern at NASA, prototyping robotic assembly, so at least your research was put to good use).
I'll reach out on Monday and see if they're still using this alignment algorithm and ask for their params + scene data. Thanks for your development work!!

**Comment by nmellado** [comment] 2018-10-09 10:16
Thanks a lot @j-polden , I'll try to work on it ASAP.

**Comment by pbeeson** [comment] 2020-08-10 19:17
This is still a problem.  I noticed that the final transformation reported from the PCL Wrapper to Super4PCS has scaling in it.  As such, the fitness function it converges to says 1.0 because it's basically matching a line.  This "bug" affects the entire problem search, as the scores being compared are potentially between different warped versions of the object model.

**Comment by nmellado** [comment] 2020-08-11 07:51
Hi @pbeeson ,

I tested with your dataset and the current version of `master`, and both the Super4PCS and the OpenGR-PCLWrapper apps give good result.

### Super4PCS
```bash
Super4PCS -i out.obj lasso_cloud_1.obj -o .99 -d 0.001 -r output_obj.ply
Starting registration
norm_max_dist: 0.001
Initial LCP: 0.125
sq_max_base_diameter_: 0.00223825        
sq_max_base_diameter_: 0.00223825        
sq_max_base_diameter_: 0.00223825         
sq_max_base_diameter_: 0.00223825         
Score: 0.555st: 0.555000                  
(Homogeneous) Transformation from lasso_cloud_1.obj to out.obj: 
 0.147943   0.16719  0.974762 -0.488616
-0.875725 -0.435865   0.20767 0.0379956
 0.459585 -0.884347  0.081929 -0.164892
        0         0         0         1
Exporting Registered geometry to output_obj.ply...
Export DONE
```

![image](https://user-images.githubusercontent.com/6310221/89871543-db1f9680-dbb7-11ea-9401-cbc1b7feb87a.png)


### PCLWrapper
```bash
OpenGR-PCLWrapper out.obj lasso_cloud_1.obj -o .99 -d 0.001
> Loading point clouds...
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
> Starting alignment...
norm_max_dist: 0.001
Initial LCP: 0.125
sq_max_base_diameter_: 0.00223825        
sq_max_base_diameter_: 0.00223825        
sq_max_base_diameter_: 0.00223825         
sq_max_base_diameter_: 0.00223825         
> Final score: 0.5550000                  
Alignment took 1561ms.

    |  0.148  0.167  0.975 | 
R = | -0.876 -0.436  0.208 | 
    |  0.460 -0.884  0.082 | 

t = < -0.489, 0.038, -0.165 >

> Saving registered cloud to output.ply ...
```


![image](https://user-images.githubusercontent.com/6310221/89871500-cba04d80-dbb7-11ea-85d2-b637beb60086.png)

**Comment by pbeeson** [comment] 2020-08-11 13:28
I didn’t provide a dataset.  That was from a previous user.  I probably
cannot send my exact dataset as it is proprietary.

However I can verify that the ComputeRigidTransform() does in fact return a
rotation matrix that SOMETIMES scales all dimensions of the object. This
tends to happen most often with an overlap > 0.2 and < 1.0.  This is
without turning on MULTISCALE.

If I edit the rigid transformation code to pass the top left 3x3 matrix of
the 4x4 transform through Eigen Quaternion, then copy the resulting
rotation matrix from the quaternion back into the 4x4 Transform, the
resulting matrix is good.  However, that fundamentally changes the computed
transform for these cases which may effect the underlying results in a
negative way (though less negatively than scaling the object away to
nothing).

Later today I can try to make a reasonable data set and code that shows
this but ultimately if the top left 3x3 Sub-matrix If the transform changes
at all When passed through a quaternion, then it’s clear it wasn’t purely
an unscaled rotation to begin with.

**Comment by nmellado** [comment] 2020-08-11 13:54
Thanks for this detailed report with testing. Having the 3d models would definitively help. 
Your experiments seems to make sense, I need to understand how we end up in such strange situation.

**Comment by pbeeson** [comment] 2020-08-11 13:55
OK, so I'll attach models and code to reproduce this in a bit, but I have verified that if I use the Super4Pcs binary, I get very different results and final scores than when using the PCL Wrapper with the same options, and the PCL one does in fact show (in the PCL window) a flattened version of the model.

`
08:49 $ Super4PCS -i scene2.ply pipe2.ply -o 1 -d 0.005 -n 50 -r output_obj.ply
(PLY) ignoring unknown element camera
Starting registration
norm_max_dist: 0.005
Initial LCP: 0
sq_max_base_diameter_: 0.00503081        
sq_max_base_diameter_: 0.00503081        
sq_max_base_diameter_: 0.00503081         
sq_max_base_diameter_: 0.00503081         
Score: 0.44est: 0.440000                  
(Homogeneous) Transformation from pipe2.ply to scene2.ply: 
 -0.950116  0.0902718  -0.298547 -0.0611904
 -0.246124   -0.80495   0.539887  0.0109532
 -0.191579   0.586435   0.787014   0.482473
         0          0          0          1
Exporting Registered geometry to output_obj.ply...
Export DONE
`
versus 

`
08:51 $ ./super_alignment ../pat_tests/scene2.ply ../pat_tests/pipe2.ply -o 1 -d 0.005 -n 50
> Loading point clouds...
> Starting alignment...
norm_max_dist: 0.005
Initial LCP: 0
sq_max_base_diameter_: 0.00503081        
sq_max_base_diameter_: 0.00503081        
sq_max_base_diameter_: 0.00503081         
sq_max_base_diameter_: 0.00503081         
> Final score: 0.6000000                  
Alignment took 106ms.
  -0.529427   -0.103028     1.25405   0.0684623
  -0.017293 -0.00577164    -0.21796    0.171072
   0.133729   -0.122346   -0.275968    0.631188
          0           0           0           1
> Saving registered cloud to output.ply ...
`

Using PCLWrapper
With -n 20:
![nonflat](https://user-images.githubusercontent.com/3858374/89905957-609f4880-dbb0-11ea-9cce-20a628189301.png)

With -n 50:
![flat](https://user-images.githubusercontent.com/3858374/89905990-6d23a100-dbb0-11ea-82ab-91c2732430b2.png)

**Comment by pbeeson** [comment] 2020-08-11 14:00
Here is the code/models

[testcode.zip](https://github.com/STORM-IRIT/OpenGR/files/5057369/testcode.zip)

**Comment by nmellado** [comment] 2020-08-11 14:02
Perfect thanks a lot, I'll have a look.
Sorry for this, the OpenGR library have changed a lot, and obviously we introduced a bug somewhere.

**Comment by pbeeson** [comment] 2020-08-11 14:25
Here is a "Patch" that I find gets around this, and doesn't appear to change the behavior of the Super4PCS binary but does change the PCLWrapper output and score.  Unsure if this should be a PR because it is actually changing the rotation matrix, which is definitely not wanted when scaling is used, but may not even be desirable given that you are crafting the rotation matrix -- of course the crafted rotation matrix seems to be adding some unwanted scaling (at least in terms of how PCL interprets it).
```
09:22 $ git diff
diff --git a/src/gr/algorithms/matchBase.hpp b/src/gr/algorithms/matchBase.hpp
index df92cee..746ee00 100644
--- a/src/gr/algorithms/matchBase.hpp
+++ b/src/gr/algorithms/matchBase.hpp
@@ -253,6 +253,10 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
             .translate(-centroid2)
             .matrix();
 
+    Eigen::Matrix3f rot = transform.block(0,0,3,3);
+    Eigen::Quaternionf q(rot);
+    transform.block(0,0,3,3) = q.toRotationMatrix();
+
     return true;
 }
```

**Comment by pbeeson** [comment] 2020-08-11 14:28
No, even with this fix, I can find cases where the object model returns flattened:
```
./super_alignment ../pat_tests/scene2.ply ../pat_tests/pipe2.ply -o 0.5 -d 0.005 -n 50
> Loading point clouds...
> Starting alignment...
norm_max_dist: 0.005
Initial LCP: 0
sq_max_base_diameter_: 0.0012577         
sq_max_base_diameter_: 0.0012577         
sq_max_base_diameter_: 0.0012577          
sq_max_base_diameter_: 0.0012577          
> Final score: 0.6000000                  
Alignment took 932ms.
 0.0747241   0.345057  0.0478452  0.0798224
  0.344132   0.871578 -0.0273793   0.150311
-0.0540985    0.01059  -0.053545   0.631462
         0          0          0          1
> Saving registered cloud to output.ply ...
```
![flat2](https://user-images.githubusercontent.com/3858374/89909794-140a3c00-dbb5-11ea-8cda-518889f70d11.png)

**Comment by pbeeson** [comment] 2020-08-11 14:34
Normalizing the 3rd vectors computed via cross product seems to fix the problem above, though I believe the final Quaternion is still needed.
```
09:33 $ git diff
diff --git a/src/gr/algorithms/matchBase.hpp b/src/gr/algorithms/matchBase.hpp
index df92cee..ea61b89 100644
--- a/src/gr/algorithms/matchBase.hpp
+++ b/src/gr/algorithms/matchBase.hpp
@@ -179,6 +179,7 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
     if (vector_p2.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
     vector_p2.normalize();
     VectorType vector_p3 = vector_p1.cross(vector_p2);
+    vector_p3.normalize();
 
     VectorType vector_q1 = q1 - q0;
     if (vector_q1.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
@@ -187,6 +188,7 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
     if (vector_q2.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
     vector_q2.normalize();
     VectorType vector_q3 = vector_q1.cross(vector_q2);
+    vector_q3.normalize();
 
     //cv::Mat rotation = cv::Mat::eye(3, 3, CV_64F);
     Eigen::Matrix<Scalar, 3, 3> rotation = Eigen::Matrix<Scalar, 3, 3>::Identity();
@@ -253,6 +255,10 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
             .translate(-centroid2)
             .matrix();
 
+    Eigen::Matrix3f rot = transform.block(0,0,3,3);
+    Eigen::Quaternionf q(rot);
+    transform.block(0,0,3,3) = q.toRotationMatrix();
+
     return true;
 }
```

**Comment by nmellado** [comment] 2020-08-11 14:45
You are right, the norm of cross product between two vectors return the area of the parallelogram formed by these vectors, which is equal to 1 only if the two vectors are orthogonal...

So this patch solves the problem:

```  patch
diff --git a/src/gr/algorithms/matchBase.hpp b/src/gr/algorithms/matchBase.hpp
index df92cee..ea61b89 100644
--- a/src/gr/algorithms/matchBase.hpp
+++ b/src/gr/algorithms/matchBase.hpp
@@ -179,6 +179,7 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
     if (vector_p2.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
     vector_p2.normalize();
     VectorType vector_p3 = vector_p1.cross(vector_p2);
+    vector_p3.normalize();
 
     VectorType vector_q1 = q1 - q0;
     if (vector_q1.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
@@ -187,6 +188,7 @@ MATCH_BASE_TYPE::ComputeRigidTransformation(const Coordinates& ref,
     if (vector_q2.squaredNorm() == 0) return std::numeric_limits<Scalar>::max();
     vector_q2.normalize();
     VectorType vector_q3 = vector_q1.cross(vector_q2);
+    vector_q3.normalize();
```

Would you consider submitting a PR with these changes + updating the contributor list, so you get credit of these changes ?
https://github.com/STORM-IRIT/OpenGR/blob/master/doc/overview.md#contributors-and-support

**Comment by nmellado** [comment] 2020-08-11 15:47
Note that this issues is also fixed in the original Super4PCS code: https://github.com/nmellado/Super4PCS/pull/69

**Closed** 2020-08-11 16:19 UTC
Labels: bug
